tabla_simbolos = {
    "feliz": ("EMOCION", "😄"),
    "triste": ("EMOCION", "😔"),
    "enojado": ("EMOCION", "😡"),
    "emocionado": ("EMOCION", "🤩"),
    "asustado": ("EMOCION", "😨"),
    "sorprendido": ("EMOCION", "😲"),
    "nervioso": ("EMOCION", "😰"),
    "relajado": ("EMOCION", "😌"),
    "confundido": ("EMOCION", "😵"),
    "aburrido": ("EMOCION", "🥱"),

    "hambre": ("ESTADO", "🤤"),
    "cansado": ("ESTADO", "😩"),
    "sueño": ("ESTADO", "😴"),
    "enfermo": ("ESTADO", "🤒"),
    "ocupado": ("ESTADO", "📋"),
    "despierto": ("ESTADO", "👀"),
    "activo": ("ESTADO", "⚡"),
    "caliente": ("ESTADO", "🥵"),
    "frío": ("ESTADO", "🥶"),
    "solo": ("ESTADO", "🚶"),

    "comiendo": ("ACCION", "🍽️"),
    "trabajando": ("ACCION", "🏢"),
    "estudiando": ("ACCION", "📚"),
    "corriendo": ("ACCION", "🏃"),
    "durmiendo": ("ACCION", "😴"),
    "leyendo": ("ACCION", "📖"),
    "escribiendo": ("ACCION", "✍️"),
    "cantando": ("ACCION", "🎤"),
    "bailando": ("ACCION", "💃"),
    "jugando": ("ACCION", "🎮"),
    "viajando": ("ACCION", "✈️"),
    "cocinando": ("ACCION", "👨‍🍳"),
    "nadando": ("ACCION", "🏊"),
    "hablando": ("ACCION", "🗣️"),
    "escuchando": ("ACCION", "🎧"),


    "pizza": ("OBJETO", "🍕"),
    "café": ("OBJETO", "☕"),
    "música": ("OBJETO", "🎶"),
    "libro": ("OBJETO", "📖"),
    "celular": ("OBJETO", "📱"),
    "computadora": ("OBJETO", "💻"),
    "televisión": ("OBJETO", "📺"),
    "balón": ("OBJETO", "⚽"),
    "bicicleta": ("OBJETO", "🚲"),
    "carro": ("OBJETO", "🚗"),
    "reloj": ("OBJETO", "⌚"),
    "dinero": ("OBJETO", "💵"),
    "regalo": ("OBJETO", "🎁"),
    "llave": ("OBJETO", "🔑"),
    "mochila": ("OBJETO", "🎒"),
    "guitarra": ("OBJETO", "🎸"),
    "cámara": ("OBJETO", "📷"),
    "helado": ("OBJETO", "🍦"),
    "pastel": ("OBJETO", "🎂"),
    "flor": ("OBJETO", "🌸"),

    # LUGARES
    "playa": ("LUGAR", "🏖️"),
    "casa": ("LUGAR", "🏠"),
    "escuela": ("LUGAR", "🏫"),
    "hospital": ("LUGAR", "🏥"),
    "parque": ("LUGAR", "🌳"),
    "restaurante": ("LUGAR", "🍴"),
    "oficina": ("LUGAR", "🏢"),
    "biblioteca": ("LUGAR", "📚"),
    "cine": ("LUGAR", "🎬"),
    "aeropuerto": ("LUGAR", "✈️"),
    "tienda": ("LUGAR", "🏪"),
    "supermercado": ("LUGAR", "🛒"),
    "gimnasio": ("LUGAR", "🏋️"),
    "iglesia": ("LUGAR", "⛪"),
    "montaña": ("LUGAR", "⛰️"),
    "bosque": ("LUGAR", "🌲"),
    "ciudad": ("LUGAR", "🌆"),
    "hotel": ("LUGAR", "🏨"),
    "estadio": ("LUGAR", "🏟️"),
    "museo": ("LUGAR", "🏛️")
}

sujetos = ["estoy", "voy", "tengo"]

reglas_semanticas = {
    "estoy": ["EMOCION", "ESTADO", "ACCION"],
    "voy": ["ACCION", "LUGAR"],
    "tengo": ["ESTADO", "OBJETO"]
}